[4.6] libct/init_linux: retry chdir to fix EPERM
projectatomic/runc pull request #44
Opened 2021-04-07 14:56 UTC by haircommander

Alas, the EPERM on chdir saga continues...

Unfortunately, the there were two releases between when https://github.com/opencontainers/runc/commit/5e0e67d76cc99d76c8228d48f38f37034503f315  was released
and when the workaround https://github.com/opencontainers/runc/pull/2712 was added.

Between this, folks started relying on the ability to have a workdir that the container user doesn't have access to.

Since this case was previously valid, we should continue support for it.

Now, we retry the chdir:
Once at the top of the function (to catch cases where the runc user has access, but container user does not)
and once after we setup user (to catch cases where the container user has access, and the runc user does not)

Add a test case for this as well.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

2021-04-08 14:14 UTC, giuseppe approved these changes
LGTM

2021-04-14 17:05 UTC, kolyshkin requested changes
Need to do something with the int tests (either drop or fix/adopt)

2021-04-15 14:59 UTC, haircommander commented
dropped the tests

2021-04-15 21:08 UTC, kolyshkin approved these changes
LGTM

2021-04-15 21:08 UTC, merged