[4.5] libct/init_linux: retry chdir to fix EPERM
projectatomic/runc pull request #45
Opened 2021-04-07 14:56 UTC by haircommander

Alas, the EPERM on chdir saga continues...

Unfortunately, the there were two releases between when https://github.com/opencontainers/runc/commit/5e0e67d76cc99d76c8228d48f38f37034503f315  was released
and when the workaround https://github.com/opencontainers/runc/pull/2712 was added.

Between this, folks started relying on the ability to have a workdir that the container user doesn't have access to.

Since this case was previously valid, we should continue support for it.

Now, we retry the chdir:
Once at the top of the function (to catch cases where the runc user has access, but container user does not)
and once after we setup user (to catch cases where the container user has access, and the runc user does not)

Add a test case for this as well.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

2021-04-08 14:14 UTC, giuseppe approved these changes
LGTM

2021-04-14 16:52 UTC, kolyshkin approved these changes
LGTM

2021-04-14 16:54 UTC, kolyshkin commented
The integration test is using too new helpers and thus won't work, needs to be adopted (mostly in setup/teardown). Not sure if we even run int tests in here.

2021-04-14 16:56 UTC, kolyshkin commented on tests/integration/cwd.bats
> +	if [[ ! -d "$AUX_DIR" || -z "$AUX_UID" ]]; then
Either add a hunk that does AUX_DIR setup as per above, or drop the tests.

2021-04-14 16:56 UTC, kolyshkin commented on tests/integration/cwd.bats
> +	teardown_bundle
This needs to be adopted to older test helpers (see other tests for examples).

2021-04-14 16:59 UTC, kolyshkin requested changes
Need to do something with the int tests (either drop or fix/adopt)

2021-04-15 14:59 UTC, haircommander commented
I dropped them

2021-04-15 21:09 UTC, kolyshkin approved these changes
LGTM

2021-04-15 21:09 UTC, merged